### ISSUE TITLE
Auto complete no longer shows local variables

### ISSUE THREAD

**Issue by ConnorAU** [SkaceKamen/vscode-sqflint#36]
After todays update, defined local variables no longer show in the autocomplete. 
I tried toggling that new context setting but it didn't help. Disabling the extension fixed it.

**Comment by SkaceKamen** [comment]
I'll look into it.

**Comment by SkaceKamen** [comment]
Oh, yea, I didn't know `findIf` existed, will add it in next update.

**Comment by Wyqer** [comment]
As far as I know findIf was fine until the update. But I can be wrong, of course.
Basically we've now many "possibly undefined variable" warnings in our code. It seems there is an issue with scopes concerning select etc.

Again a picture which shows this strange behaviour.

![localvariable](https://user-images.githubusercontent.com/3811977/47347300-3b75d900-d6af-11e8-9c7f-f4146d618b9a.png)

**Comment by SkaceKamen** [comment]
Yea, that's because the system for checking correct combinations of commands is now more aggressive and won't allow to just put something that isn't defined in middle of expression.

For the false positives, I forgot to add support for lambda functions (eg functions used in select and such) ... I'll have to work on that, in the meanwhile you can just disable the context aware checking.

**Comment by Wyqer** [comment]
No critical problem at all, just wanted to report it. :)
I'm looking forward for the upcoming updates and really appreciate your work.

**Comment by SkaceKamen** [comment]
This issue is fixed in 0.9.1, issue with inline functions moved to #37
